---
title: "The Enduring Significance of Neighborhoods"
format: html
toc: true
editor: visual
---

## Description

A primary theme of our class has been the enduring significance of neighborhoods for housing. We've looked at how these patterns of differentiation oftentimes overlay down to the block with patterns of racial and economic segregation. We've also looked at a range of policy tools used to address segregation and disinvestment in neighborhoods. So why despite all of these efforts are there such marked differences between neighborhoods and their power to support intergenerational wealth transfer and mobility?

### Discussants

Fatima and Juliana

## Learning Goals

-   Understand arguments for why segregation remains a major social and policy issue within the United States.
-   Critically question the role of government in contributing to segregation.
-   Question emerging grounds for the creation and sustaining of disparities across space and over time.

## Readings

Rotella, Carlo - *The Unexpected Power of Your Old Neighborhood* [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/nbjpi9k1c592bg52o96s6fsl2er39vmw)

Prochaska, Natalie - *"Old" URban Renewal in Champaign-Urbana, 1960-1969* [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/0r8dngderxe99n4kya11h0r0q3pmavk4)

Governing Magazine Segregated in the Heartland Series [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/ab9t9nm0wkpk1w1durlctke3cqwwgxus)

-   How States and Cities Reinforce Racial Segregation in America [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/l1u9uvck6nuovybmncyx5e5zjqrz3fzp)
-   How Schools Fuel White Flight [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/wy8xt2y2gnpwrxkb2m916lamygt8qgef)
-   How Housing Policies Keep White Neighborhoods so White and Black Neighborhoods So Black [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/80opkndukixmoiev7ill1vzo1inu8p1f)
-   How Police and Anti-Crime Measures Reinforce Segregation [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/tj2hlkoxlj89avpou8icinwfxcmrnjmg)

## Slides

## Additional Resources

-   Galster, George, and Patrick Sharkey - *Spatial Foundations of Inequality A Conceptual Framework* [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/x6ujv7t7grpvz2czsj2n0hhe6fpzssnm)

-    [Baker, Dwayne, Esteban Lopez, and Andrew Greenlee, Transit Development and Housing Displacement: The Case of the Chicago Red Line Extension](https://www.tandfonline.com/doi/full/10.1080/14036096.2017.1284155)

-    [Black Activity Spaces in Shaker Heights  ](https://www.tandfonline.com/doi/full/10.1080/26884674.2021.1972774)

<!-- -->

-    [Contractor, Annie, and Andrew Greenlee, Up-"Routing" Communities: Subaltern Voices Challenge Sustainable Urban Renewal in Fortaleza, Brazil](https://www.tandfonline.com/doi/full/10.1080/14036096.2017.1284155)

-    [Keep, Miriam, Bernadette Montanari, Andrew Greenlee, Contesting "inclusive" development: Reactions to Slum Resettlement as Social Inclusion in Tamesna, Morocco](https://www.sciencedirect.com/science/article/pii/S0264275121002286)

-    [Lee, et al., Transcriptomic Analyses of Black Women in Neighborhoods with High Levels of Violence](https://www.sciencedirect.com/science/article/pii/S0306453021000482)

-    [Lee, C. Aujean, and Andrew Greenlee, Impacts of Multiscale Racial Concentration on Neighborhood Foreclosure Risk in Immigrant Gateway etropolitan Areas](https://journals.sagepub.com/doi/abs/10.1111/cico.12478)

-    [Sutton, Stacey, Urban Revitalization in the United States: Policies and Practices (Sections 2-4)](https://uofi.box.com/s/ea307xgwlws48lu97msi9cqbjo8yfjr9)
