---
title: "Neighborhood Change"
format: html
toc: true
editor: visual
---

## Description

This week we will explore the causes and consequences of neighborhood change. We will examine some of the theory surrounding neighborhood change, and, drawing from local and national examples, we'll look at the ways in which analysts qualify outcomes from this change over time.

## Learning Goals

-   Understand the common economic and social theories that explain neighborhood change.
-   Articulate why neighborhood change often becomes a political issue.
-   Critically engage with how narratives of neighborhood change influence the social, economic, and political futures of neighborhoods.

## Readings

Smith, Neil, Gentrification and the Rent Gap [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/j14auc1u7z2ejkfrktv0sl9agy930x43)

Saunders, Pete, The State of Gentrification [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/n384sdn09lum3j0lpxr0vmcslzsfe7fi)

Ellen, Ingrid, and Justin Steil, The Dream Revisited: Contemporary Debates about Housing Segregation and Opportunity (Discussion 24) [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/778pqakd8ffofk1lnfksfnqb2bstsv3c)

Voorhees Center, The Socioeconomic Change of Chicago's Community Areas (1970 - 2010) [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/f5fzu7ofv0udoaaimnebdlsz2ac7r3t6)

Voorhees Center, Gentrficiation and Neighborhood Change: Helpful Tools for Communities (skim) [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/d9q26wyr9mkkqzjsk9hzoqe99quhs5mh)

## Slides

## Additional Resources

-   [Beck, Brenden, The Role of Police in Gentrification  ](https://uofi.box.com/s/uoi7f89ccudnpgtut9pvx9prq0t8retp)

-    Greenlee, Andrew - [Assessing the Intersection of Neighborhood Change and Residential Mobility for the Chicago Metropolitan Area (2006-2015)](https://www.tandfonline.com/doi/full/10.1080/10511482.2018.1476898)

-    Greenlee, Andrew and Beverly Wilson - [Where Does Location Choice Drive Residential Mobility? An Analysis of Origin and Destination Communities](https://besjournals.onlinelibrary.wiley.com/doi/10.1002/pan3.10096)

-    Lopez, Esteban, and Andrew Greenlee - [An Ex-Ante Analysis of Housing Location Choices Due to Housing Displacement: The Case of Bristol Place](https://www.sciencedirect.com/science/article/pii/S0143622816303472)

-    [Sims, J. Revel, and Carolina Sarmiento, The Affordable Housing Complex: Direct and Exclusionary Displacement in the Lacy and Logan Neighborhoods in Santa Ana, California  ](https://uofi.box.com/s/r8298vbirr8eza4ueg1emidow3kcrlqm)

-    There Goes the Neighborhood

    -    [Miami, Part 1](https://www.wnycstudios.org/podcasts/the-stakes/episodes/the-stakes-there-goes-neighborhood-miami-1)

    -    [Miami, Part 2](https://www.wnycstudios.org/podcasts/the-stakes/episodes/the-stakes-there-goes-neighborhood-miami-2)

    -    [Miami, Part 3](https://www.wnycstudios.org/podcasts/the-stakes/episodes/the-stakes-there-goes-neighborhood-miami-3)

-    [The Social Breakdown: Gentrification: Movement in Neighborhoods](https://www.thesocialbreakdown.com/2021/09/15/soc502-gentrification-movement-in-neighborhoods-guest-edition/)

-    [The Social Breakdown: Gentrification Through Food](https://www.thesocialbreakdown.com/2020/11/11/soc408-gentrification-through-food/)
