---
title: "Housing Special Populations"
format: html
toc: true
editor: visual
---

## Description

Our nation's housing delivery system works well for some, but there are other specialized populations that require additional outreach and support. This week, we will examine the unique housing needs of both homeless individuals and individuals with disabilities, and will explore the range of policy tools and strategies to provide inclusive, long-term housing solutions.

## Learning Goals

-   Understand common standards for measuring homelessnes.
-   Understand how local continuums of care provide services.
-   Recognize common barriers to housing for people with disabilities.
-   Envision how housing policy might respond to the housing needs of an ageing population.

## Readings

Schwartz 12

Introduction to *The Undeserving Poor* by Michael Katz [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/t3guayooalijagatwqm1s5kg3x66tlrx)

State of Homelessness 2022 (skim) [{{< fa arrow-up-right-from-square >}}](https://endhomelessness.org/homelessness-in-america/homelessness-statistics/state-of-homelessness/)

Last Week Tonight - Homelessness

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/liptMbjF3EE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

PBS News Hour - How More Americans are "Aging in Place"

<iframe width="560" height="315" src="https://www.youtube.com/embed/5VqgSkN14JE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

## Slides

## Additional Resources

-    99% Invisible: According to Need

    -    [Chapter 1: Tulicia](https://99percentinvisible.org/episode/according-to-need-chapter-1-tulicia/)

    -    [Chapter 2: The Hotline](https://99percentinvisible.org/episode/according-to-need-chapter-2-the-homelessness-hotline/)

    -    [Chapter 3: Housing First](https://99percentinvisible.org/episode/according-to-need-chapter-3-housing-first/)

    -    [Chapter 4: The List](https://99percentinvisible.org/episode/according-to-need-chapter-4-the-list/)

    -    [Chapter 5: Housing Finally](https://99percentinvisible.org/episode/according-to-need-chapter-5-housing-finally/)

-    Seattle Times - [She Didn't Want to Die Homeless. But in Seattle, There Were Few Places To Turn.](https://www.seattletimes.com/seattle-news/homeless/she-didnt-want-to-die-without-a-home-but-even-with-cancer-she-had-few-options-in-seattle/)

-    [Together as a Family: Multigenerational Living Rises in a Pandemic](https://www.washingtonpost.com/realestate/together-as-a-family-multigenerational-living-rises-in-pandemic/2021/05/12/bd8598f6-a900-11eb-8d25-7b30e74923ea_story.html)
