---
title: "Schedule"
format: html
editor: visual
---

Our course schedule is subject to change over the course of semester - please check here often for updates.

+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week    | Dates   |         | Description                                                          | Discussant(s) |
+=========+=========+=========+======================================================================+===============+
| Week 1  | 1/18/23 |         | [Course Introduction](01_introduction.qmd)                           |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 2  | 1/23/23 | 1/25/23 | [How Well Are we Housed?](02_housed.qmd)                             |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 3  | 1/30/23 | 2/1/23  | [Government Intervention in Housing](03_government.qmd)              |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 4  | 2/6/23  | 2/8/23  | [Homeownership](04_homeownership.qmd)                                | Tillie        |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Dorian        |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 5  | 2/13/23 | 2/15/23 | [Public Housing](05_publichousing.qmd)                               | Zane          |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 6  | 2/20/23 | 2/22/23 | [Federally Assisted Housing](06_fedassisted.qmd)                     | Erica         |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 7  | 2/27/23 | 3/1/23  | [Housing Production Strategies](07_production.qmd)                   | Rafi          |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Temka         |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 8  | 3/6/23  | 3/8/23  | [The Enduring Significance of Neighborhoods](08_neighborhoods.qmd)   | Fatima        |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Juliana       |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 9  | 3/13/23 | 3/15/23 | [Spring Break](09_break.qmd)                                         |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 10 | 3/20/23 | 3/22/23 | [Regulating Housing Environments](10_hsgenv.qmd)                     | Margaret      |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 11 | 3/27/23 | 3/29/23 | [Eviction](11_eviction.qmd)                                          | Fiona         |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Daisy         |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 12 | 4/3/23  | 4/5/23  | [Neighborhood Change](12_neighborhoodchg.qmd)                        | Colt          |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Caelin        |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 13 | 4/10/23 | 4/12/23 | [Housing Market Discrimination and Fair Housing](13_fairhousing.qmd) | Dominique     |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 14 | 4/17/23 | 4/19/23 | [Housing Special Populations](14_specialpop.qmd)                     |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 15 | 4/24/23 | 4/26/23 | [Independent Work and Advising](15_indwork.qmd)                      |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 16 | 5/1/23  | 5/3/23  | [Class Presentations and Course Wrap-Up](16_wrapup.qmd)              |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
