---
title: "Course Resources"
format: html
editor: visual
---

## Assignment Resources

-    [UP 473 Housing Indicator Data and Code](https://github.com/agreen4/UP-473-S22-Code) repository contains both data and R code to download common housing indicators including those that are specifically called for in your assignments. Please note that the code available here is for your reference. You do not have to use R or similar tools to perform your analysis.

-    [Professional Writing By the Numbers](https://uofi.box.com/s/8sd9ievwu7gumwg5co5eqy9ebrj3k4vg) - a reference manual by [Dr. Edward Feser](https://leadership.oregonstate.edu/provost/about/provost-edward-feser) on professional writing for policy professionals.

-    Professor Greenlee\'s [Memorandum Writing Tips](https://uofi.box.com/s/50nw1lyan59mbkji1wfqpm8fv3uei1w1)

-    Annotated [Memorandum Example](https://uofi.box.com/s/9ns3krmvac54qxtmjtswhvx29l9rx5a7)

-    [How to Write a Policy White Paper](https://uofi.box.com/s/6himjv9jps7anh6j4p3bwvkrlznagc31)

-    [How to Write and Format a White Paper: The Definitive Guide](https://uofi.box.com/s/1ic054dyvhjrk5m21qtditqbe6dpxi2e)

-    White Paper Examples

    -   Chicago Metropolitan Agency for Planning: [Expanding Housing Choice Strategy Paper](https://uofi.box.com/s/b39c61z2803bgs25zlbqbmma3hzgknch)

    -   San Mateo County Board of Supervisors: [Affordable Housing White Paper: Preventing Displacement and Promoting Affordable Housing Development in San Mateo County](https://uofi.box.com/s/ks0nzi8k050pyzf1oo4wkrro297t4gx2)

    -   Seattle Planning Commission: [Family-Sized Housing: An Essential Ingredient to Attract and Retain Families with Children in Seattle](https://uofi.box.com/s/rpn4swv9bye89212gdprldq91iqi4xjy)

    -   City of Evanston: [Affordable Housing White Paper](https://uofi.box.com/s/vc6xu00rmdwxb4xapxhd3nq5w9rrd85p)

-    [UIUC instructions](https://faq.library.illinois.edu/faq/151721) for accessing New York Times and other newspaper articles.

## Housing Advocacy and Research - Illinois

-    [Access Living Chicago](https://www.accessliving.org/)

-    [Chicago Rehab Network](https://www.chicagorehab.org/)

-    [Cunningham Township Supervisors Office](https://www.toi.org/township/champaign-county-cunningham-township/)

-    [DePaul Institute for Housing Studies](https://www.housingstudies.org/)

-    [Habitat for Humanity of Champaign County](https://cuhabitat.org/)

-    [Housing Action Illinois](https://housingactionil.org/)

-    [Land of Lincoln Legal Aid](https://lincolnlegal.org/)

-    [Nathalie P. Voorhees Center for Neighborhood and Community Improvement](https://voorheescenter.uic.edu/)

-    [Shriver Center on Poverty Law](https://www.povertylaw.org/)

-    [Woodstock Institute](https://woodstockinst.org/)

\

## Housing Advocacy and Research - National

-    [Center on Budget and Policy Priorities](https://www.cbpp.org/)

-    [NYU Furman Center](https://furmancenter.org/)

-    [Kirwan Institute for the Study of Race and Ethnicity](https://kirwaninstitute.osu.edu/)

-    [National Coalition for the Homeless](https://nationalhomeless.org/) \* [National Initiative on Mixed-Income Communities](https://case.edu/socialwork/nimc/)

-    [National Low-Income Housing Coalition](https://nlihc.org/)

-    [Portland State University Homelessness Research & Action Collaborative](https://www.pdx.edu/homelessness/)

-    [Poverty & Race Research Action Council](https://www.prrac.org/)

-    [Shimberg Center for Housing Studies](http://www.shimberg.ufl.edu/)

-    [UC Berkeley Terner Center for Housing Innovation](https://ternercenter.berkeley.edu/)

-    [University of Florida Shimberg Center for Housing Studies](http://www.shimberg.ufl.edu/)

-    [University of Minnesota Center for Urban and Regional Affairs](https://www.cura.umn.edu/)

-    [UNC Center for Urban and Regional Studies](https://curs.unc.edu/)

-    [UNC Center for Community Capital](https://communitycapital.unc.edu/)

-    [Urban Institute](https://www.urban.org/research-area/housing-and-housing-finance)

## Housing Data

-    [American Community Survey](https://www.census.gov/programs-surveys/acs/data.html)

-    [American Housing Survey](https://www.census.gov/programs-surveys/ahs.html)

-    [Brown S4 Longitudinal Tract Database](https://s4.ad.brown.edu/projects/diversity/Researcher/LTBDDload/Default.aspx)

-    [Census Household PULSE Survey: Measuring Household Experiences During the Coronavirus Pandemic](https://www.census.gov/data/experimental-data-products/household-pulse-survey.html)

-    [Eviction Lab](https://evictionlab.org/)

-    [Harvard Joint Center for Housing Studies](https://www.jchs.harvard.edu/)

-    [HUD-USPS Vacancy Data](https://www.huduser.gov/portal/datasets/usps.html)

-    [National Assocation of Realtors](https://www.nar.realtor/research-and-statistics)

-    [National Housing Preservation Database](https://preservationdatabase.org/)

-    [Zillow.com](https://www.zillow.com/research/)

\

## Periodic Email Lists

-   [HUDUser](https://www.huduser.gov/portal/subscribe/subscribe.html): HUD Office of Policy Development and Research newsletter.

-   [National Low-Income Housing Coalition Call on HoUsed: Universal, Stable, Affordable Housing](https://nlihc.org/covid-19-working-groupcalls): Weekly calls, many including members of Congress to discuss issues related to affordable housing and covid housing recovery.

-   [Urban Institute Housing Matters](https://www.tfaforms.com/4644066?tfa_1927=HM): Weekly newsletter on national housing policy.
