---
title: "Housing Needs Analysis"
format: html
toc: false
editor: visual
---

In your second assignment, you described elements of housing supply and demand and also identified the specific housing consumers present within your housing market. For this assignment, you will spend more time thinking about the housing needs associated with these consumers. Specifically, you will draw from elements of HUD's Assessment of Fair Housing methodology to analyze your housing market's demographics, patterns of spatial integration and segregation, and the intersectionality between housing and other needs. Together with your Housing Market Analysis, your Housing Needs Analysis will constitute the basis for your final assignment -- a housing policy platform -- which will focus on designing intervention to address the needs you identify within your local housing market.

Drawing from the [HUD AFFH Guidebook](https://www.hud.gov/sites/dfiles/FHEO/documents/AFFH-Rule-Guidebook.pdf) and the [HUD AFFH Data](https://www.hud.gov/program_offices/fair_housing_equal_opp/affh), analyze the needs present within your local housing market. At a minimum, your housing needs analysis should address the following:

-   **Demographic Summary:** Describe demographic patterns in the housing market and describe trends over time. Describe the location of homeowners and renters in the housing market, and describe trends over time.

For further guidance, see the AFFH Rule Guidebook §5.5.1.

-   **Segregation and Integration:** Describe and compare segregation levels in the housing market and region. Identify the racial and ethnic groups that experience the highest levels of segregation. Explain how these segregation levels have changed over time.

Identify areas with relatively high segregation and integration by race/ethnicity, national origin, or LEP group, and indicate the predominant groups living in each area.

Consider and describe the location of owner and renter occupied housing in determining whether such housing is located in segregated or integrated areas. Discuss how patterns of segregation have changed over time.

Discuss whether there are any demographic trends, policies, or practices that could lead to higher segregation in the jurisdiction in the future.

For further guidance, see the AFFH Rule Guidebook §5.5.2

-   **Concentration of Poverty:** Identify any R/ECAPs or groupings of R/ECAP tracts within the jurisdiction. Which protected classes disproportionately reside in R/ECAPs compared to the housing market and region?

Describe how R/ECAPs have changed over time.

For further guidance, see the AFFH Rule Guidebook §5.5.3

-   **Access to Opportunity:** Describe disparities in access to opportunity, including access to education, employment, transportation, low poverty exposure, and environmentally healthy neighborhoods, as well as any overarching patterns relating to access to opportunity in the region.

Identify and discuss any overarching patterns of access to opportunity and exposure to adverse community factors based on race/ethnicity, national origin, or familial status. Identify areas that experience an aggregate of poor access to opportunity and high exposure to adverse factors.

For further guidance, see the AFFH Rule Guidebook §5.5.4

-   **Disproportionate Needs:** What groups by race/ethnicity and family status experience higher and severe rates of housing cost burden, overcrowding, or substandard housing when compared to others?

Which areas in the housing market experience the greatest housing burdens, and how do these burdens align with segregated areas, integrated areas, R/ECAPs, and what is the predominant race/ethnicity or national origin group in such areas?

For further guidance, see the AFFH Rule Guidebook §5.5.5

-   **Disability and Access:** How are persons with disabilities geographically dispersed or concentrated in the housing market, including R/ECAPs and other segregated areas identified in previous sections? Describe whether these geographic patterns vary for persons with each type of disability or for persons with disabilities in different age ranges.

To what extent do persons with disabilities in or from the jurisdiction or region reside in segregated or integrated settings?

For further guidance, see the AFFH Rule Guidebook §5.5.7

After analyzing these dimensions of housing needs, provide an overall summary of housing needs present within your housing market, and an assessment of how these needs relate to those within the broader region. As part of your summary, identify one or two priority populations based upon your assessment of needs and housing impacts within your housing market, and describe the needs of these populations. The priority populations which you identify will constitute the focus of your housing policy platform (your final assignment).

### Deliverable 

Prepare your assessment as a memorandum of around 3,000 words. Your memorandum should include sufficient analysis and properly referenced evidence for another housing market expert to measure the strength and validity of your assertions. The judicious use of maps, imagery, and tables should be included to support your analysis.

### Data Notes 

You will need to construct your own summaries from the AFFH Raw Data -- please note that this process is time-consuming -- leave yourself plenty of time to work through this. For more specifics on data and indicators, please also see HUD's data documentation.

### Assignment Submission 

Please submit your paper electronically via Canvas.

\
