---
title: "Term Paper"
format: html
toc: false
editor: visual
---

Doctoral students in UP 473 will produce a term-length paper on a topic of your choice that draws upon the academic literature to engage with a theme related to housing policy. Based upon your interests and needs, this paper could include original empirical analysis of a phenomenon, could be theory-based, or could be focused on synthesizing literature. We will work together to determine an appropriate paper scope and approach. In addition to preparing your term assignment, you will present your paper to the class at the end of the semester.

Your completed term paper will be due at the end of the semester. In order to ensure that you are making adequate progress to meet this deadline, you will submit several intermediate work products including the following:

-   **Term Paper Proposal:** a 1-page term paper proposal

-   **Extended Abstract:** an extended abstract and paper outline

-   **Literature Review:** a review of relevant literature.

Your final term paper should be between 8,000 and 10,000 words in length (excluding references).

### Assignment Submission 

-    Term Paper Proposal: submit via email to Professor Greenlee

-    Extended Abstract and Outline: submit via email to Professor Greenlee

-    Literature Review: submit via email to Professor Greenlee

-    Complete Term Paper: submit via email to Professor Greenlee

\
